package com.tippingpoint.sql;

import java.util.Iterator;
import com.tippingpoint.database.Column;
import com.tippingpoint.database.ColumnDefinition;
import com.tippingpoint.database.ColumnTypeId;
import com.tippingpoint.database.Table;

/**
 * This class is use to generate the command to insert into a row into a table.
 */
public class SqlInsert extends TableBuilderCommand {
	/**
	 * This method constructs a new statement for the given table.
	 */
	public SqlInsert(final Table table) {
		super(table);
	}

	/**
	 * This method is a convenience method used to add the relevant columns from the table to the insert statement. Note
	 * that columns that are typically generated by the database (e.g. ID columns) are not added to the statement.
	 */
	public void addColumnsForTable() {
		final Iterator<ColumnDefinition> iterColumns = m_table.getColumns();
		while (iterColumns.hasNext()) {
			final Column column = iterColumns.next();
			if (!(column.getType() instanceof ColumnTypeId)) {
				add(new ParameterizedValue(column, null));
			}
		}
	}

	/**
	 * This method returns the string representation of the SQL command.
	 */
	@Override
	public String toString() {
		return "Insert " + m_table;
	}
}
