package com.tippingpoint.database;

/**
 * This class represents a column type of ID.
 */
public class ColumnTypeId extends ColumnTypeIdBase {
	public static final String TYPE = "id";

	/**
	 * This method constructs a new column type.
	 */
	protected ColumnTypeId() {
		super(TYPE);
	}

	/**
	 * This method returns if the value is derived based on the database.
	 */
	@Override
	public boolean idDerived() {
		return true; // ids are derived in the database
	}

	/**
	 * This method returns if the type dictates if the value is required when the column is required. Values not
	 * required when the column type indicates that the column is specified are values generated by the database (i.e.
	 * id columns).
	 */
	@Override
	public boolean isValueRequired(final boolean bColumnRequired) {
		// id columns are required in the database, but not necessarily in the statements
		return false;
	}

	/**
	 * This method gives a changes for the type to set any restrictions on the column type.
	 * 
	 * @param columnDefinition ColumnDefinition being defined by this type.
	 */
	@Override
	public void setRestrictions(final ColumnDefinition columnDefinition) {
		// all id columns are required in the database
		columnDefinition.setRequired(true);
	}
}
